dist: xenial
language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install pytest-cov codecov

script:
  - pytest -v --cov

after_success:
  - codecov

deploy:
  provider: pypi
  user: coady
  password:
    secure: QTriI5GbyuBYXi6eQ2LaJht6vWc3Q/13dtclKmZSofsDQjnObMiEmT8kfeQkV/0Wxq/3iOa42Yg8Gwn+cj8eNQvQIf8WTzzvATMlAxrEN/ZmFDA4qYqsyI5p2z6GbMianrtA9PyWYLHmNou+Je1/gq9ugcUjcaJ1cJrxQ5N4jCtBKDHu86HX59V9dqWF81RXs/nDk8XygGuwAhYfkFlKjrwK++5RKDSe9DHfPq38SZtPRVPZM15NrB+nKAdjzo6t0VaJF8E1IMhrIcZhUjEMycpJBWIf5pW/gISELRADyPobG59SSUlDdMfF8NdwkUiqroUlpyLg03+EZlfzX8wBpxi93dZzVWlGwsa449fpFlGaFbdKezk+GAfAxNtlHsCYPdjfl+FHDcElZAN++3gK9Fa811Et4jx4NEE/2SSkT9gmTJwu2iURmFoe5kpvtVswFqg4RKlv2ouVlJw87l2pwPF7C3XIysEneIe2G4ZABiQp6ufoliqOw94yMjNfOjxWd+LtHsRSW5bQFaXBH/zY2HEDG8DOWueA6MDRv3IhNleaQuwkSCRFx4E55cMcnBQ0KbXaaKRmoGtmeGVYEzRzs31wr+UkmjV7SA117icOo+rAlI1CNpQvYAajeM7ED5eiFIA8OS9dO96JZnp9OEvDZVe1wNVEj0WBL+Rf0KbTsG4=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
